### ISSUE TITLE
Эндпоинты

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-server#10]
Можно вместо того, чтобы использовать названия эндпоинтов, передавать тип запроса. Таким образом будет например не ```/getUsers``` и ```/createUser```, а просто ```/users```. Для  получения будет передаваться ```GET```, для создания ```POST```

**Comment by gshumilin** [comment]
Готово. Названия эндпоинтов, которые отвечают за редактирование сущностей, трогать не стал.
