### ISSUE TITLE
Hlint

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-server#11]
Исправить все предупреждения, которые выдает hlint

**Comment by pavelzarubin** [comment]
Еще и ormolu подключи. Даже так, лучше сначла пусть отработает ormolu. Сделай коммит. Потом уже исправляй ошибки которые hlint выдает.

**Comment by gshumilin** [comment]
Я применил команду `ormolu --mode inplace $(git ls-files '*.hs')` и незначительно поменялся только один файл. Похоже, у меня в расширении hlint для VSCode уже было зашито редактирование, да?

**Comment by pavelzarubin** [comment]
по идее форматер зашит в какое-то из расширений vscode
