### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-server#12]
- [x] Нет обработки ошибки, при потере соединения с базой.
- [x] Нет обработки ошибки, наличия базы данных.
- [x] Для соединения с базой лучше использовать [пул](https://hackage.haskell.org/package/resource-pool) соединений, а не одно.

**Comment by gshumilin** [comment]
3) Я добавил пул соединений. Посмотри, пожалуйста, прежде чем я перейду к другим пунктам.

**Comment by gshumilin** [comment]
закрывать ишью не буду, пока не реализую обработку ошибок в новой структуре
