### ISSUE TITLE
Поле numbersOfPictures у типа Types.DB.News.News

### ISSUE THREAD

**Issue by olegromashin** [gshumilin/learning-server#26]
Можешь объяснить зачем добавлено поле `numbersOfPictures`? Может его можно удалить?

**Comment by gshumilin** [comment]
В задании требуется обеспечить возможность сортировки новостей по кол-ву картинок. В типе Domain.News, в котором новости возвращаются пользователю, этого поля нет. Пользователь кол-во картинок не получит. А вот в DB.News я эту информацию просто не спрятал.

Запрос на получение и сортировку новостей формируется в функции makeInitReadNewsQuery из DatabaseQueries.QueryCreator. Сейчас посмотрю, получится ли использовать кол-во картинок для сортировки, но не создавать для этого колонку и не возвращать её как результат.

**Comment by gshumilin** [comment]
Разобрался. Убрал добавление колонки "number_of_pictures" из секции SELECT. Изменил способ добавления сортировки к запросу, когда клиент напишет "sort_by=order_of_pictures". Теперь в результате получится запрос, где в секции ORDER BY будет агрегатная функция COUNT
