### ISSUE TITLE
Новости

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-server#8]
- [x] Почему при редактировании можно изменить id автора, если только сам автор может изменять новость. Так быть не должно.
- [x] При обновлении новостей нет изменения статуса новости, есть только при создании и то ```false```.
- [x] Зачем в новостях есть поле для числа картинок?

**Comment by gshumilin** [comment]
1. У эндпоинта editNews нет параметра для изменения id автора. Изменять id автора нет возможности. А вот в самом хэндлере есть неудачный нейминг поля oldCreatorId. Оно содержит информацию об авторе и не изменяется. UserId клиента сравнивается с этим полем, если совпадает, то редактирование новости доступно. Исправил, чтобы не было недопонимания. Теперь это creatorId

**Comment by gshumilin** [comment]
2. Добавил параметр для редактирования статуса новости. Добавил его и в тестовые реквесты

**Comment by gshumilin** [comment]
3. Информация о числе картинок нужна была для сортировки по количеству картинок. Сама сортировка производится на стороне базы данных. Для клиента эта информация не так важна, но я решил оставить. В задании требования вернуть кол-во картинок нет, так что удалил.

**Comment by pavelzarubin** [comment]
> 1. У эндпоинта editNews нет параметра для изменения id автора. Изменять id автора нет возможности. А вот в самом хэндлере есть неудачный нейминг поля oldCreatorId. Оно содержит информацию об авторе и не изменяется. UserId клиента сравнивается с этим полем, если совпадает, то редактирование новости доступно. Исправил, чтобы не было недопонимания. Теперь это creatorId

ну так почему бы не сделать эту проверку при получении новости для редактирования, ты же можешь получить новость по id новости и по id создателя, тогда в сущности ```EditedNewsFields``` не будет лишнего поля, которое и нарушает логику. Кстати ты так и достаешь из базы нужную новость. Базе данных не доверяешь?

**Comment by gshumilin** [comment]
Да, можно и так. Кажется, я сначала так и сделал, но просто потом решил по возможности не перекладывать логику на postgres, а реализовать это в хэндле. Чтобы тесты на это написать. Поменял

**Comment by pavelzarubin** [comment]
Просто у тебя и в базе проверка и в коде. По мне так это излишне. Лучше оставить только в базе.
