### ISSUE TITLE
Картинки

### ISSUE THREAD

**Issue by pavelzarubin** [gshumilin/learning-server#9]
При добавлении картинок тип никак не проверяется, можно спокойно вместо картинки аудио файл добавить.

**Comment by gshumilin** [comment]
Исправил. Обрати, пожалуйста внимание на putPicture. Этот эндпоинт вообще не нужен для задания, я создавал его для самостоятельного тестирования базы. Но вот в чём проблема:

Он не в хэндле, поэтому для него пришлось отдельно реализовать функцию проверки поля mime. Это норм?

**Comment by pavelzarubin** [comment]
ну вообще его бы убрать, раз он только тобой используется. Либо сделать просто тестировочную функцию для добавления только картинок, чтоб тестить  getPicture.

**Comment by gshumilin** [comment]
Удалил putPicture и функцию writePicture, которую этот эндпоинт использовал.
